### ISSUE TITLE
Ability to register data for consumption by an external app

### ISSUE THREAD

**Issue by Quazia** [AutarkLabs/aragon.js#12]
In order to provide information directly between applications that may not exist in the app contract state, we need to create API endpoints to pass required data between applications. There are two main use cases for this, information that has been pinned to IPFS but hasn't triggered an event in the target app (data is still pending a forwarder action to trigger and become available in the main application) and information that only exists in a call script. The former is likely a subset of the latter but has enough difference to be thought of separately. In both cases, we'll most likely be expecting this data to be available in a forward, although we should make an effort to support cases beyond this. At minimum data blobs should have the following parameters attached to them:
1. `from` - The application initially generating the information; this should take the form of an address as it's the most accessible unique identifier for an application.
2. `to` - The application (or applications) we want to have access to this information. This should probably be an array of addresses. It's possible this may be redundant/we don't need to have this property but it should ease the filtering of data for target applications.
3. `actionId/dataId` -  This is an _internal_ unique identifier for the information attached to this action or data set as determined by the application that's initially creating the data. For a standard forwarder interaction, this will most likely be the actionId received from the forwarder API. The important part is this is a unique identifier in the context of the app this data blob originates from.
4. `cid` - this is the _external_ unique identifier used to look up the data blob. This will most likely be an IPFS hash or an IPFS data variant. This content could also provide things like raw HTML to render in the receiving application, schemas to decode the data, or even components to render in the target application. Since there's no limit on what can be stored here we put the obligation of security on the application developer and can avoid decoding this data within the client.

In order to pass this information between an application of *origin* and a *target* we need to make the following changes to aragon.js:

### Registration Flow
- [ ] Create a `registerAppMetadata` in `aragon-api/src/index.js` - this endpoint needs to receive the parameters described above and pass them to the messenger. It must also be fully tested in `aragon-api/src/index.test.js`
- [ ] There needs to be an `appMetadata` observable created in `aragon-wrapper/src/index.js` - This requires creating an initialization function, and registering the appropriate handlers. The initialization of this observable should be tested in `aragon-wrapper/src/index.test.js`
- [ ] The correct RPC handlers need to be added in order to receive the `registerAppMetadata` request from the API. This should take the form of a `register-app-metadata.js` file in `aragon-wrapper/src/rpc/handlers/index.js`.

### Consumption Flow
- [ ] Create a `getAppMetadata` in aragon-api/src/index.js` - this endpoint shouldn't need any parameters. It must also be fully tested in `aragon-api/src/index.test.js`
- [ ] The correct RPC handlers need to be added in order to receive the `getAppMetadata` request from the API. This should take the form of a `get-app-metadata.js` file in `aragon-wrapper/src/rpc/handlers/index.js`. This function should only return data relevant to the application the request is coming from, so data should be filtered based on the `to` property of the addMetadata observable with respect to the application that initiated the request. This function must also be tested in the `aragon-wrapper/src/rpc/handlers/` folder.
